services:
  db:
    image: postgres:15-alpine
    container_name: habit_tracker_db
    environment:
      POSTGRES_USER: habit_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: habit_tracker
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U habit_user -d habit_tracker"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  api:
    build: .
    container_name: habit_api
    ports:
      - "5093:8080"
    depends_on:
      db:
        condition: service_healthy
      mailhog:
        condition: service_started
    dns:
      - 8.8.8.8
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # БД
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=habit_tracker
      - DB_USER=habit_user
      - DB_PASSWORD=${DB_PASSWORD}
      # JWT
      - JWT_SECRET=${JWT_SECRET}
      # Погода, AI
      - WEATHER_BASE_URL=${WEATHER_BASE_URL:-https://api.openweathermap.org/data/2.5/}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - AI_BASE_URL=${AI_BASE_URL:-https://api.groq.com/openai/v1}
      - AI_API_KEY=${AI_API_KEY}
      - AI_MODEL=${AI_MODEL:-llama3-8b-8192}
      # SMTP через MailHog
      - EmailSettings__SmtpServer=mailhog
      - EmailSettings__SmtpPort=1025
      - EmailSettings__SenderEmail=noreply@habittracker.local
      - EmailSettings__SenderName=Habit Tracker
      - EmailSettings__Login=
      - EmailSettings__Password=
      - EmailSettings__EnableSsl=false
      # Базовый URL для ссылки подтверждения
      - AppBaseUrl=http://localhost:5093
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog
    container_name: habit_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped

volumes:
  postgres_data:
